### ISSUE TITLE
Legacy file picker

### ISSUE THREAD

**Issue by Lucky390163** [abdallahmehiz/mpvKt#105]
Legacy file picker is absent.I have to pick videos one by one to play.

**Comment by venttarc** [comment]
I agree. A file picker like vlc or any other video player will be very very helpful.

**Comment by abdallahmehiz** [comment]
same as #24 
Will be adding it once i find the time

**Comment by Lucky390163** [comment]
Thanks, it will be helpful and can you add this.[
![Screenshot_20240929_105743_VLC](https://github.com/user-attachments/assets/7851fcef-f05b-4542-96c2-aa6dd96b51bd)
](url).
Thanks,
Regards Lucky

**Comment by abdallahmehiz** [comment]
> Thanks, it will be helpful and can you add this.[ ![Screenshot_20240929_105743_VLC](https://private-user-images.githubusercontent.com/115852216/371825045-7851fcef-f05b-4542-96c2-aa6dd96b51bd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODgwNjUsIm5iZiI6MTcyNzU4Nzc2NSwicGF0aCI6Ii8xMTU4NTIyMTYvMzcxODI1MDQ1LTc4NTFmY2VmLWYwNWItNDU0Mi05NmMyLWFhNmRkOTZiNTFiZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNTI5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTllMjFiOTNmOWE3YjI5Y2Y5MWYzYjg1OTg4NTM0NzIzNGEwNzI2MDZjOTAxOGZlMjRiMmFiZjI0NjU4MzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oIm2DGlepdtUdgVwOyUOPdltjLjPJUCEgkoDFtVORTQ) ](url). Thanks, Regards Lucky

There's already HW, HW+ and SW decoding settings in the video UI and a "Try hardware decoding" setting in the decoder settings that substitute what you sent...

**Comment by Lucky390163** [comment]
Thanks.
