### ISSUE TITLE
How to use lua or js script

### ISSUE THREAD

**Issue by ahaoboy** [abdallahmehiz/mpvKt#107]
**Describe the bug**

I want to use some mpv scripts, but I can't find any relevant documentation or examples. Does mpvKt support the use of scripts?

**Comment by abdallahmehiz** [comment]
Yes! Here are the steps
1. Set an mpv configuration directory from advanced settings
2. Put your scripts and all it needs in that directory the same way you put them in a computer's ~/config/mpv directory 
That's it

**Comment by ahaoboy** [comment]
> 1. Set an mpv configuration directory from advanced settings
> 2. Put your scripts and all it needs in that directory the same way you put them in a computer's ~/config/mpv directory
>    That's it


I created a mpvkt folder in the document directory and set it as the configuration folder of mpvkt
I created a file, the path is /document/mpvkt/config/mpv/test.lua, It seems to work, the script uses osdMessage to display a number

But I have encountered some problems:
- If I delete the lua script file and restart the app, it still works? And the js script in the same directory does not work
- If the ~/mpv.conf file is modified in other software, then reopening mpvkt will not update to the latest value?

Why not use the same naming as the desktop? For example ~/portable_config/scripts, and in which folder would custom fonts go? ~/config/fonts?

**Comment by abdallahmehiz** [comment]
>     * If I delete the lua script file and restart the app, it still works? And the js script in the same directory does not work

That's because behind the scenes, mpvKt is copying the scripts to its files directory for mpv to be able to use it. if you want to clear that too you can find a button in the advanced settings to do so.

>     * If the ~/mpv.conf file is modified in other software, then reopening mpvkt will not update to the latest value?

I've explicitly gave priority to using the mpv.conf file from external storage, so modifying it *should* override the current one.

**Comment by ahaoboy** [comment]
> I've explicitly gave priority to using the mpv.conf file from external storage, so modifying it _should_ override the current one.

Thank you for your explanation. I think I understand. That is, mpvkt will copy the files in scrips to another place. In this way, if you modify the content of the script file, it will be overwritten after moving, so the modification will take effect. However, deleting the script will not do the same operation. Therefore, the script can only be deleted by clearing the cache in the app. Am I right?

**Comment by abdallahmehiz** [comment]
Yes

**Comment by ahaoboy** [comment]
> Yes

But it seems that mpvkt does not support mujs scripts? I added mujs support to mpv-android before, but I can't find the code compiled by mpvkt

https://github.com/mpv-android/mpv-android/pull/922

**Comment by abdallahmehiz** [comment]
> But it seems that mpvkt does not support mujs scripts? I added mujs support to mpv-android before, but I can't find the code compiled by mpvkt

Not yet at least, since I am currently using the master branch of mpv-android which doesn't support it either.

**Comment by ahaoboy** [comment]
> Ok, cleaned things a bit and the script works. Is it possible to bind it to a gesture though?

As far as I know, the mpv-android script does not support UI operations, otherwise we can use uosc directly in Android

**Comment by ahaoboy** [comment]
> > > Ok, cleaned things a bit and the script works. Is it possible to bind it to a gesture though?
> > 
> > 
> > As far as I know, the mpv-android script does not support UI operations, otherwise we can use uosc directly in Android
> 
> You're talking about something else. In MPV-Android it's possible to set the gesture to `custom` and bind it to toggle script via `input.conf` and `0x10003 script-binding skipsilence/toggle` for right side double tap.
> 

That' cool~ This might run mpv-easy, However, mujs does not support it yet.

**Comment by SShwinA** [comment]
> Ok, cleaned things a bit and the script works. Is it possible to bind it to a gesture though?

Could you share how you got it to work?

**Comment by abdallahmehiz** [comment]
> I don't care about those at all, just want to be able to toggle lua scripts under default mpvKt gui.

That's a bit too out of scope, but we've added something similar recently, can you check the nightlies?

**Comment by abdallahmehiz** [comment]
I'll consider this issue solved
