### ISSUE TITLE
Feature Request: Subtitles get cut off at bottom when cropping 2.40:1 widescreen video; need auto-adjust or touch-friendly subtitle adjust

### ISSUE THREAD

**Issue by Pentaphon** [abdallahmehiz/mpvKt#114]
When I press the zoom button to crop a 2.40:1 aspect video so it fits better inside my screen, the subtitles get cut off at the bottom. 

Could you provide a way to auto-adjust the subtitles to stay in the screen when cropping video or some touch-friendly way to move subtitles up and down?

**Comment by abdallahmehiz** [comment]
You can already do that in the subtitles customization panel

**Comment by Pentaphon** [comment]
> You can already do that in the subtitles customization panel

Ah, I see it now. I didn't realize it was tucked into the player's subtitle button and then that palette icon. Closing.
