### ISSUE TITLE
App has unexpected error on opening

### ISSUE THREAD

**Issue by Ryder9013** [abdallahmehiz/mpvKt#127]
**Describe the bug**
I opened the app today, it said "mpvKt experienced an unexpected error"

**To Reproduce**
1. Open the app
2. See error

**Expected behavior**
App should open normally 

**Actual behavior**
Unexpected error

**Additional info**
Upon clicking restart the app button it works normally now

**Crash logs**
[mpvKt_logs.txt](https://github.com/user-attachments/files/17531081/mpvKt_logs.txt)

**Screenshots**
![Screenshot_20241026-205140](https://github.com/user-attachments/assets/50649905-81df-4df8-9ce2-c529321aa252)

**Additional info (please complete the following information):**
 - Device: Nothing Phone 2a
 - Android version: 15
 - App Version: 0.1.6

**Comment by abdallahmehiz** [comment]
the steps, don't reproduce the issue...

**Comment by Ryder9013** [comment]
> the steps, don't reproduce the issue...

😅 The above crash happened randomly yesterday. I don't know what caused it, it just happened on opening the app.
