### ISSUE TITLE
Video Sharpness!

### ISSUE THREAD

**Issue by Vincracked** [abdallahmehiz/mpvKt#140]
So I was watching apothecary diaries and noticed Mx player pro and Vlc have more sharpness . Now I am not sure If Mx player pro and vlc adds artifical sharpness , I want to watch the episode as intended without adding any of the artifical sharpness . I just want to know if Mpvkt is lacking sharpness or Mx and vlc have artifical sharpness?

**Comment by abdallahmehiz** [comment]
Probably not
Can you send some comparisons screenshots?

**Comment by abdallahmehiz** [comment]
If you want to add extra sharpness, look into
Look into
https://mpv.io/manual/stable/#options-sharpen
For some sharpening options

**Comment by Vincracked** [comment]
> If you want to add extra sharpness Look into https://mpv.io/manual/stable/#options-sharpen For some sharpening options



> Probably not Can you send some comparisons screenshots?

I wanted to share screenshots but for some reason mx player and vlc screenshots gets faded out

**Comment by Vincracked** [comment]
> I can't do much without solid comparisons... might just be placebo or your OS is artificially sharpening the videos for vlc and mx player (a bit far fetched but can happen)...

The video is a normal x264 video playing through Hw+ decoding . The device is Redmi Pad ( 2022 ) . I noticed it and now My apothecary binge is on hold🫠 , someone help me

**Comment by abdallahmehiz** [comment]
I can't proceed with this issue without reproducible examples/comparisons
