### ISSUE TITLE
Sharpness! ( with images )

### ISSUE THREAD

**Issue by Vincracked** [abdallahmehiz/mpvKt#143]
it was very hard to capture but 

![IMG_20241105_220347_457](https://github.com/user-attachments/assets/c06659fc-75e9-4447-825b-23a41ea8745e)
![IMG_20241105_220409_6](https://github.com/user-attachments/assets/4133ccde-75fc-44d7-8e4c-7911e720741f)

First one is mx player pro/vlc 
second is mpv

As you can see the image from mx player looks very "sharp" as compared to mpv "soft"

Device - Redmi pad ( 2022 )

**Comment by abdallahmehiz** [comment]
You used your phone to capture these images? From another screen?
Why not screenshot?
Sorry but I can't possibly use these images.

**Comment by Vincracked** [comment]
Because ss of mx player/vlc gets faded out

**Comment by abdallahmehiz** [comment]
doesn't address my question...
