### ISSUE TITLE
Cannot Position Subtitles !

### ISSUE THREAD

**Issue by Vincracked** [abdallahmehiz/mpvKt#144]
Look 
![Screenshot_2024-11-08-17-04-31-562_live mehiz mpvkt](https://github.com/user-attachments/assets/33cbf32c-5903-489b-98a5-721bd0ed612d)
( Mpv ) 

![Screenshot_2024-11-08-17-05-03-149_com mxtech videoplayer pro](https://github.com/user-attachments/assets/2226ee4f-1462-4635-8360-5083db938579)
( How it should look )

I tried positioning , but nothing changes

**Comment by abdallahmehiz** [comment]
You're using them as a secondary subtitle

**Comment by Vincracked** [comment]
How do I use them as primary??

**Comment by Vincracked** [comment]
![Uploading Screenshot_2024-11-08-17-11-35-540_live.mehiz.mpvkt.jpg…]()

**Comment by Vincracked** [comment]
![Screenshot_2024-11-08-17-13-17-777_live mehiz mpvkt](https://github.com/user-attachments/assets/bed78dc2-4ba6-4c41-a1ee-a7ea70c961f2)

No worries , Overriding .ass subs Works
