### ISSUE TITLE
(feature request) subtitles spacing

### ISSUE THREAD

**Issue by aswinachuu** [abdallahmehiz/mpvKt#147]
just asking can you add a subtitle spacing option? like if there is two lines of subtitles, can you add an option to adjust the space between them? if it isn't possible, its ok <3
thanks

**Comment by Vincracked** [comment]
+1

Here is the comparison b/w mx and mpvkt
![IMG_20241109_110308_264](https://github.com/user-attachments/assets/93f3a8ac-bcbd-43d8-a2a4-ebe1a6700833)
![IMG_20241109_110307_886](https://github.com/user-attachments/assets/6d005219-2905-49cc-a82a-13932bf660a3)

The gap is more in mpv and its kinda annoying

**Comment by abdallahmehiz** [comment]
you can use `ass-line-spacing` for that

**Comment by Vincracked** [comment]
> you can use `ass-line-spacing` for that

It works but Looks like the default value is "1" and if I lower it to say "0.9 , 0.8 " it doesn't work.
Looks like it only works with value " 1-100 "

**Comment by abdallahmehiz** [comment]
That's probably the minimum line height then.

**Comment by aswinachuu** [comment]
> you can use `ass-line-spacing` for that

anyways i love the subtitle customisation!
and also what about adding a manual zoom in and out feature (zooming with 2 fingers like in mx player and others)

**Comment by aswinachuu** [comment]
![Screenshot_20241110-192948_mpvKt](https://github.com/user-attachments/assets/df69a958-2792-4cc2-8984-d9122899c420)
![Screenshot_20241110-192959_mpvKt](https://github.com/user-attachments/assets/47bbc656-f64f-473e-9459-11ce28d06f10)
not for me tho i love the subtitle customization

**Comment by abdallahmehiz** [comment]
I guess this is a solved issue.
