### ISSUE TITLE
Player doesn't show up in list of external players

### ISSUE THREAD

**Issue by Monirzadeh** [abdallahmehiz/mpvKt#15]
Some place mpvKt missing in player list so I can't select mpvKt (usually stream apps lik jellyfin or newpipe etc)
For example install newpipe and in settings -> video and audio -> Player -> user external player
activate this than play a youtube video mpvKt missing in list of Avilable player.

**Comment by abdallahmehiz** [comment]
Huh... Weird, it should in theory be listed there.
Even App Manager's interceptor lists in the Matching activities section
![Screenshot_20240901-105726](https://github.com/user-attachments/assets/099384ee-a408-483d-8085-881e2a1ff62a)
I'll be taking a look at it soon, thanks for the report.

**Comment by abdallahmehiz** [comment]
I think I've fixed it, but to be sure, can you try it out with the nightly build?
https://github.com/abdallahmehiz/mpvKt/actions/runs/10661758753
