### ISSUE TITLE
(Future Request) to Add Regional Language Subtitle Support in Player

### ISSUE THREAD

**Issue by spike395** [abdallahmehiz/mpvKt#150]
I would like to request the addition of subtitle support for regional languages (such as Hindi, Bengali, and others) in mpvKt player.
![Screenshot_20241110_100756](https://github.com/user-attachments/assets/b1dd6e4a-8dfd-403d-8073-609a6aa88573)

**Comment by abdallahmehiz** [comment]
It should be fixed after the next mpvlib bump

**Comment by spike395** [comment]
Thank You Sir 😊
