### ISSUE TITLE
ver:0.1.6-251 chapter seek issue 

### ISSUE THREAD

**Issue by Singout69** [abdallahmehiz/mpvKt#159]
I have noticed that v251 fails to skip chapters 
If I select chapter 2 it doesn't skip to chapter 2 it just buffer and restart from the chapter that I'm currently on 
![Screenshot_2024-11-25-20-07-15-78_b93262821ba13b7694bb5d76b5032d4b](https://github.com/user-attachments/assets/9b562264-23aa-4f9d-ae45-e31b73190826)

**Comment by abdallahmehiz** [comment]
That's a regression on my end, sorry.
I'll push a fix later today.
