### ISSUE TITLE
[Feature request] Subtitle delay utility

### ISSUE THREAD

**Issue by 77-77SP** [abdallahmehiz/mpvKt#17]
I would to suggest a subtitle delay utility similar to what VLC has where the application will calculate the time difference between the "Text seen" and the "Audio heard" buttons and set it as the delay value.

**Comment by abdallahmehiz** [comment]
I've actually kind of attempted something similar while adding the subtitles delay panel.
Here's what i came up with at the time

https://github.com/user-attachments/assets/c6b6a121-c656-49e6-8261-28e87949dc9f

This design has the one flaw of not supporting negative subtitles delay.
And it's also kind of confusing the users from the feedback i got at the time.
I don't really want to copy VLC's implementation one-to-one so I'll try doing it differently again some other time.
