### ISSUE TITLE
Crashes right after you select a video to play

### ISSUE THREAD

**Issue by omarelmahdy2200** [abdallahmehiz/mpvKt#172]
**Describe the bug**
Just after you choose a video this crash log appears before even starting the video
![image](https://github.com/user-attachments/assets/ec539726-cc0f-4d14-a9dc-b03a6ff999c5)

**To Reproduce**
1. open file picker
2. select a video
3. See error

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Crash logs**
[mpvKt_logs.txt](https://github.com/user-attachments/files/18049210/mpvKt_logs.txt)

**Screenshots**

**Additional info (please complete the following information):**
 - Device: Realme 11
 - Android version: 14
 - App Version: the current one on the play store

**Additional context**

**Comment by abdallahmehiz** [comment]
Try unsettling your mpv.conf directory location, or recreating the mpv.conf file missing that location.
This has already been fixed in the nightlies.
