### ISSUE TITLE
Add build scripts

### ISSUE THREAD

**Issue by gamernoob24** [abdallahmehiz/mpvKt#174]
For the people who want to build their own app

**Comment by abdallahmehiz** [comment]
The application doesn't need any buildscripts though?
All you have to do is clone, allow git to execute commands in the cloned dir and just run `./gradlew assemble`

**Comment by gamernoob24** [comment]
oh thanks but when i run
``./gradlew assemble``
it only builds the app not its other libraries that depend on it (eg. mpv, ffmpeg)

**Comment by abdallahmehiz** [comment]
That's how it should be, other libraries are fetched from online sources and repositories to be used, you don't have to compile everything.
If you want to check how mpv and ffmpeg are compiled check my https://github.com/abdallahmehiz/mpv-android repo

**Comment by gamernoob24** [comment]
i guess i am fine with that
