### ISSUE TITLE
Video choppy, and will not let me swap decoding methods

### ISSUE THREAD

**Issue by CoolPenguin42** [abdallahmehiz/mpvKt#183]
**Describe the bug**
Unable to swap decode methods. On mpv-android base, swapping on sw/hw the video is choppy af, hw+ it is nice and smooth as usual. On this fork, unable to swap between sw/hw/hw+, so it's stuck on sw. video is choppy

**To Reproduce**
1. start a video
2. Click on and hold decode method to open popup
3. click on hw/hw+, nothing happens

**Expected behavior**
should swap decode modes and see notable behavior, as demonstrated by me doing the same thing on mpv-android main and it works as intended there

**Actual behavior**
nothing swaps, vid stays choppy

**Crash logs**
N/A

**Screenshots**
N/A

**Additional info (please complete the following information):**
 - Device: samsung tab s5e
 - Android version: 11
 - App Version: 0.1.6

**Additional context**

**Comment by abdallahmehiz** [comment]
try enabling yuv420p in the settings.

**Comment by CoolPenguin42** [comment]
> try enabling yuv420p in the decoder settings.

Thanks! Turned out that setting was already on, turning it off fixed it! Thanks for pointing me to the correct setting :)
