### ISSUE TITLE
Test builds

### ISSUE THREAD

**Issue by Buxuna** [abdallahmehiz/mpvKt#2]
I want to test the app and give feedback since official mpv android ui is crap and dont support scripts . Here do I find test builds ?
Or am I too early that test builds are not ready yet ?

**Comment by abdallahmehiz** [comment]
> I want to test the app and give feedback since official mpv android ui is crap and dont support scripts . Here do I find test builds ? Or am I too early that test builds are not ready yet ?

i still consider the app incomplete as it's missing a lot of features and qof fixes. I also haven't implemented any tests for it so expect to crash.
as for early builds you can get them from the preview workflow's artifacts [here](https://github.com/abdallahmehiz/mpvKt/actions/workflows/preview.yml).

**Comment by Buxuna** [comment]
Thank you very much , the ui is quite good and I love the dual subtitle selection . I hope keyboard support will be added soon .

**Comment by abdallahmehiz** [comment]
I've started uploading pre-releases now so I'am close this.
