### ISSUE TITLE
[Feature Request] Reduce motion setting

### ISSUE THREAD

**Issue by Monirzadeh** [abdallahmehiz/mpvKt#21]
Currently when you tap on screen elements show with a moving animation.
Can change that to a simple fade animation (all element show with each other) instead of move over screen to get in place.  Make working with ui faster too if it be a quick fade(I thinkcurrent animation is a little slow)

When you tap screen became dark to ui element see more easily. Can it be a little less darker or contorae in settings?

**Comment by 77-77SP** [comment]
Doesn't the app already adhere to the system animation settings? I have the **Remove animation** setting enabled and I do not seem to notice any animations in the app.

I would like to add that the delay could be hardware related if you are using a low-end device (As it is in my case). I noticed that it happens to me in every application that implements Material 3. In that case, I do not think that it is an app-specific issue.

**Comment by 77-77SP** [comment]
I would like to add that the only delay I experience is when I open the player's UI. Any optimization effort is greatly appreciated. Thank you for your commitment!

**Comment by abdallahmehiz** [comment]
> I would like to add that the delay could be hardware related if you are using a low-end device (As it is in my case). I noticed that it happens to me in every application that implements Material 3. In that case, I do not think that it is an app-specific issue.

I would blame the delay from tapping to ui appearing on Jetpack Compose's onTap function having an obscenely long and unchangeable delay.

**Comment by Anthonyy232** [comment]
I believe this solves that
https://github.com/abdallahmehiz/mpvKt/pull/121
