### ISSUE TITLE
Play Store availability

### ISSUE THREAD

**Issue by abdallahmehiz** [abdallahmehiz/mpvKt#22]
The app has been on its way to the Play Store for a while.
But because of Google's 20 testers policy, it hasn't been going smoothly...

So for users who want to access the app through the Play Store for now, here's how you can:
1. Join this google group with the account you use on Play Store: https://groups.google.com/g/mpvkt-testing
2. Access the app on the Play Store from this link: https://play.google.com/apps/testing/live.mehiz.mpvkt

Downloading it from Play Store also helps in getting accepted and maybe publishing it there.

**Comment by Abu3safeer** [comment]
Done, you should mention this request in the README

**Comment by remlap** [comment]
Same reinstalled from there few days ago.

**Comment by abdallahmehiz** [comment]
If the production application gets rejected again, I'll be adding this to the readme.
![Screenshot_20240913-224435](https://github.com/user-attachments/assets/c5dc7fe6-350e-4b83-bae5-2be3d415f520)

**Comment by Abu3safeer** [comment]
Hope it gets approved, I will spread it on anime community, they really needs this since this app support ASS subtitles almost perfectly. 

The original version of mpv lacks support for custom fonts, this makes watching any ASS subtitle a horrible experience, but with mpvkt I have no issues at all, this should be on Google play store, people do not know they need it!

**Comment by abdallahmehiz** [comment]
> Hope it gets approved, I will spread it on anime community, they really needs this since this app support ASS subtitles almost perfectly.
> 
> The original version of mpv lacks support for custom fonts, this makes watching any ASS subtitle a horrible experience, but with mpvkt I have no issues at all, this should be on Google play store, people do not know they need it!

Well I've got some good new, the production application got accepted, I've created a production release but it's still "under review". It'll be published soon hopefully. Thank you for the support🙏.

**Comment by abdallahmehiz** [comment]
:partying_face: It has been finally been published https://play.google.com/store/apps/details?id=live.mehiz.mpvkt
