### ISSUE TITLE
chapters not showing

### ISSUE THREAD

**Issue by Brajesh3** [abdallahmehiz/mpvKt#23]
mpvKt
![Screenshot_20240902-165044_mpvKt](https://github.com/user-attachments/assets/12ac63a2-6993-48d5-b280-9f85111505cf)
![Screenshot_20240902-165054_mpvKt](https://github.com/user-attachments/assets/404fa0a6-6313-47ed-b27c-e41c9a0378a2)

mpvKt-settings
![Screenshot_20240902-165235_mpvKt](https://github.com/user-attachments/assets/979c4b9d-4b0b-4dbd-8567-868805853f92)

mpv-android
![Screenshot_20240902-165132_mpv+ytdl](https://github.com/user-attachments/assets/a9d2feeb-f6db-4e81-b205-c892ea279e32)
![Screenshot_20240902-165145_mpv+ytdl](https://github.com/user-attachments/assets/afcb4430-4dfd-4573-9d38-34400767a00a)

**Comment by abdallahmehiz** [comment]
Looks like I've made a regression...

**Comment by abdallahmehiz** [comment]
Sorry for the inconvenience caused by this, You can use the nightly release that shouldn't have this bug now. I will make sure to test my changes properly from now on. Again, sorry for the inconvenience.

**Comment by Brajesh3** [comment]
Thank you for the quick fix! I'm impressed by how fast you addressed this issue—getting it resolved in just 20 minutes is amazing. I appreciate the dedication to testing and improving the project. Keep up the great work!
