### ISSUE TITLE
[Bug] Status Bar and Navigation Bar stuck and doesn't hide

### ISSUE THREAD

**Issue by jeyemrs** [abdallahmehiz/mpvKt#25]
https://github.com/user-attachments/assets/589e0f45-ca15-46f3-88ec-f5e56b952499

Basically, this happens when I'm using the gestures. I'm not sure if it also happens to other devices or Android versions.

Edit:
~I gotta add something, the episode on the screen recording supposed to have chapters, but it doesn't show on the mpvKt.~ It seems like it's already fixed on the latest commit. I didn't see it haha

**Comment by abdallahmehiz** [comment]
> It seems like it's already fixed on the latest commit. I didn't see it haha

I didn't change any logic regarding your issue though...

**Comment by abdallahmehiz** [comment]
Reminds me... I should make a bug report template

**Comment by Sumitdesu** [comment]
This happens with me too on Redmi note 8 pro (Android 11), the full-screen indicator doesn't hide.

**Comment by abdallahmehiz** [comment]
should be fixed in 4eb4bccc83f4a28b1d17ba2625f6f9ba0fc584f6
can you check in the nightly?
