### ISSUE TITLE
Chapters missing in 0.1.3

### ISSUE THREAD

**Issue by BhaturaGuy** [abdallahmehiz/mpvKt#26]
Chapter gaps in timeline
Chapter buttons
Chapter indicator

All 3 are missing in v 0.1.3

**Comment by Brajesh3** [comment]
It's fixed
Just download from latest build [https://github.com/abdallahmehiz/mpvKt/actions/runs/10666581166](https://github.com/abdallahmehiz/mpvKt/actions/runs/10666581166)

**Comment by abdallahmehiz** [comment]
Yes, it's a regression sorry I am for making...
