### ISSUE TITLE
[Bug] Full-screen indicator doesn't hide

### ISSUE THREAD

**Issue by Sumitdesu** [abdallahmehiz/mpvKt#27]
Full-screen indicator doesn't hide when playing videos.

Device: Redmi note 8 pro
Android version: 11
mpvKt version: 0.1.3 (latest as of now)

https://github.com/user-attachments/assets/c8844048-d184-4ebc-84d9-ec2b776b0039

**Comment by kyklish** [comment]
Same issue: 

1. Open video file 
2. Add external audio file (shows Android controls) 
3. Android controls not hide anymore :(

Android 11
mpvKt 0.1.3

![Screenshot_20240903-111106.png](https://github.com/user-attachments/assets/e7e1088a-c9d1-4871-b0a4-4ae0964debb0)

**Comment by kyklish** [comment]
It's appears spontaneously. Double tap for pause some times shows Android controls or interaction with UI buttons during playback :/
