### ISSUE TITLE
[Feature request] Switch lock icons

### ISSUE THREAD

**Issue by nvllz** [abdallahmehiz/mpvKt#32]
I think a filled closed padlock icon when locked and an unlocked padlock outline when unlocked would be a better way to represent this setting.

**Comment by abdallahmehiz** [comment]
Now that you mention it, I've been using the Filled variant this entire time... But the Outlined variant gets displayed instead, this might be a bug from the MaterialIconsExtended library
![image](https://github.com/user-attachments/assets/61d1112b-4827-4f62-aa26-67838f802f2a)
