### ISSUE TITLE
Subtitles background is no longer visible

### ISSUE THREAD

**Issue by nvllz** [abdallahmehiz/mpvKt#36]
**Describe the bug**
Since the 0.1.4 update I can't see the subtitles background regardless of color/alpha channel settings.

**Additional info (please complete the following information):**
 - Device: galaxy s23
 - Android version: 14
 - App Version: Release v0.1.4

**Comment by abdallahmehiz** [comment]
seems to have been caused by this
https://github.com/mpv-player/mpv/issues/14777
an easy fix

**Comment by abdallahmehiz** [comment]
should be fixed, can you check the nightly to make sure?
