### ISSUE TITLE
crash on choosing external subs

### ISSUE THREAD

**Issue by t-e-s-tweb** [abdallahmehiz/mpvKt#4]
below are logs

it doesn't happen if the video is playing in SW decoder then you can choose subtitle and later switch to HW. however if the video is playing in HW and then you load subtitles then this crashes. 

[mpvKt_logs.txt](https://github.com/user-attachments/files/16736255/mpvKt_logs.txt)

**Comment by abdallahmehiz** [comment]
can you try on latest pre-release?
