### ISSUE TITLE
The app loads video a lot while seeking

### ISSUE THREAD

**Issue by NikunjKhangwal** [abdallahmehiz/mpvKt#40]
The app starts loading video whenever I seek. I'm assuming the app doesn't import the full video right away. This just doesn't happen when seeking forward but backward too, even tho the player has already went past the previous parts of video and they should be played instantly. I think it doesn't keep the video in ram? I've already tried changing the decoder options.
Now admittedly I'm on a low-end device but at the same time this doesn't happen in MX, vlc and xplayer. I hope you can identity and fix it.

**Comment by NikunjKhangwal** [comment]
Idk if it's a known issue or not. But let me know if you need a screen recording or something.

**Comment by abdallahmehiz** [comment]
Would adding an option to disable previews while seeking be a good enough solution for you?

**Comment by NikunjKhangwal** [comment]
Previews seem to work fine in other apps.

Also It's not just about seeking but skipping the video forward and backward too. Idk what's c1ausing it but probably a problem related to base mpv. I wish i could help further but i'm not a developer. See if you can find something otherwise you can close the issue.

**Comment by abdallahmehiz** [comment]
Just to be sure, are you seeking from the seekbar or by using gestures?

**Comment by Brajesh3** [comment]
When seeking video both the loading & seeking indicator apears at the same time.
I think when seeking only seeking indicator should appear & when it's loading there should be loading indicator.

**Comment by abdallahmehiz** [comment]
> Ah! Now that you mention it gestures doesn't seem to have this problem. There's minor loading but that's normal. I was using seekbar.

Yes, since the I've made it so seeing with the seekbar is precise, but gestures aren't.

**Comment by NikunjKhangwal** [comment]
Great. Thanks a lot
