### ISSUE TITLE
[feature request] volume boost 

### ISSUE THREAD

**Issue by Sensex00** [abdallahmehiz/mpvKt#46]
Sometimes webdl movies and web series have very lower volume so it will good to boost volume more than 100 percent like in vlc and MX player

**Comment by abdallahmehiz** [comment]
I've implemented this in the https://github.com/abdallahmehiz/mpvKt/tree/volume_boost branch and I kind of need some feedback on it.
If anyone is willing to test it and give feedback, check the nightly builds https://github.com/abdallahmehiz/mpvKt/actions/runs/10755591258

**Comment by Sensex00** [comment]
I check I was playing video on system decoder and it was not working my volume was Max at 15 and it did not go beyond that where it should have option to go to 30

**Comment by abdallahmehiz** [comment]
> I check I was playing video on system decoder and it was not working my volume was Max at 15 and it did not go beyond that where it should have option to go to 30

The volume boost isn't using any system APIs though, I am just increasing the volume of mpv.
That number (15), is the number of volume steps from 0 to max volume. It is given to me by the system.
It should keep the max at 15 and then increase mpv volume to your preference (30 default) resulting in something like 15+30

**Comment by abdallahmehiz** [comment]
> > I check I was playing video on system decoder and it was not working my volume was Max at 15 and it did not go beyond that where it should have option to go to 30
> 
> The volume boost isn't using any system APIs though, I am just increasing the volume of mpv. That number (15), is the number of volume steps from 0 to max volume. It is given to me by the system. It should keep the max at 15 and then increase mpv volume to your preference (30 default) resulting in something like 15+30.

(The number of steps on some phones changes, like my friend's realme had a 16 step slider with 16 being "200%" in his realme android skin, while another (poco x3 pro) had the number of steps be 100 for some reason)

**Comment by Sensex00** [comment]
Ok I think you should implement volume and brightness system like orginal mpv and vlc where it show as percentage% by this it will not inconsistency accross any device and it will show like this

![Screenshot_2024-09-08-13-11-53-804_org videolan vlc](https://github.com/user-attachments/assets/8882a93a-4be0-419f-b24a-ddcb49d6ff0d)

And you volume boost 200% and there will be message show up like this at 100% maybe it will take time but this solution will almost perfect for all

**Comment by Sensex00** [comment]
![Screenshot_2024-09-08-13-26-39-916_live mehiz mpvkt preview](https://github.com/user-attachments/assets/4ddf07b6-bc90-4e72-979b-efed4e73fab3)

This is capped at 15 not going to 30 and I didn't notice any difference didn't understand what said earlier can you please provide any link to where we could talk or please reply herewith

**Comment by abdallahmehiz** [comment]
Are you sure you're on the correct nightly build?
Cause increasing volume past the limit should look like this
![Screenshot_20240908-090644](https://github.com/user-attachments/assets/2b82f1bb-ed10-4414-9c01-35c19356b6c6)

**Comment by Sensex00** [comment]
> Are you sure you're on the correct nightly build? Cause increasing volume past the limit should look like this ![Screenshot_20240908-090644](https://private-user-images.githubusercontent.com/54363735/365423159-2b82f1bb-ed10-4414-9c01-35c19356b6c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODMyMzQsIm5iZiI6MTcyNTc4MjkzNCwicGF0aCI6Ii81NDM2MzczNS8zNjU0MjMxNTktMmI4MmYxYmItZWQxMC00NDE0LTljMDEtMzVjMTkzNTZiNmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjZjMzZkMTA4N2EyZDU4ZjNjODRmYzEwZDA2YzZiODI5MDQzYmI4MTgwM2I2YTRkNmU1YTA1N2IyNTllY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Wo8sewgd8VCROpU47l9O3jGZNDpxdMDzBbxlz2bqmQ)

Yes I downloaded from your link and it was updated version

**Comment by abdallahmehiz** [comment]
> Yes I downloaded from your link and it was updated version

Check the audio settings for a volume boost setting, make sure it's not disabled

**Comment by Sensex00** [comment]
I uninstalled whole app and installed again but didn't know why it was not being updated but telling me it was updated successfully after updating nightly build

**Comment by Sensex00** [comment]
Now it's working
