### ISSUE TITLE
[Bug] Not Showing All Chapters

### ISSUE THREAD

**Issue by jeyemrs** [abdallahmehiz/mpvKt#47]
**Describe the bug**
I tried 3 videos and it only shows the first one chapter for each videos.

**To Reproduce**
1. Play a video
2. Click chapters
3. It will only show 1 chapter

**Expected behavior**
it should show all of the chapters available for the video.

**Actual behavior**
It just shows 1 chapter

**Screenshots**
![Screenshot_20240906-210653](https://github.com/user-attachments/assets/752e8e50-6b68-4c97-b7c2-bfb6b1ac3a95)

**Additional info (please complete the following information):**
 - Device: Infinix Note 11s
 - Android version: 11
 - App Version: Release v0.1.4 & Preview v0.1.4-174

**Additional context**
mkv video format. Idk if that matters.

**Comment by abdallahmehiz** [comment]
> This may be yet another issue with Android 11 and below. Man, I need to upgrade phone now lol

No it's actually a regression I've made somewhere, sorry for the inconvenience.
