### ISSUE TITLE
load subtitle/audio from URL missing

### ISSUE THREAD

**Issue by aicynide** [abdallahmehiz/mpvKt#50]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Crash logs**
If applicable, upload a the text file provided by the app's crash screen.

**Screenshots**

**Additional info (please complete the following information):**
 - Device: [e.g. Google Pixel 6]
 - Android version: [e.g. 13]
 - App Version [e.g. Release v0.1.3, Nightly v0.1.3-r151]

**Additional context**

**Comment by abdallahmehiz** [comment]
... Please follow the Bug report template.

**Comment by abdallahmehiz** [comment]
Yes I've seen it, it is planned, just not a priority right now
