### ISSUE TITLE
Can you check this bug 

### ISSUE THREAD

**Issue by Sensex00** [abdallahmehiz/mpvKt#56]
When I wanted to clear the mpv.conf it was crashed only solution was to first clear the pick location configuration and then clear the conf in mpv.conf

[mpvKt_logs-1.txt](https://github.com/user-attachments/files/16921647/mpvKt_logs-1.txt)

**Comment by abdallahmehiz** [comment]
What steps did you do for this crash to happen (PLEASE use the bug report template!).

**Comment by Sensex00** [comment]
https://github.com/user-attachments/assets/60e6fed9-ae0e-4be8-86a2-870163b42cb0

I don't know why it happened but now when I tried to reproduce it was not crashing earlier when I cleared the movie.conf and clicked on ok it crashed 
You can close I guess
