### ISSUE TITLE
Add save position brightness display

### ISSUE THREAD

**Issue by MrDark-code** [abdallahmehiz/mpvKt#58]
Hi now the svp player stores the position of the display brightness, you need to add it here.

https://github.com/mpv-android/mpv-android/blob/92be55335dfd12834620e6fd5dc84b46bb79f7c1/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L1892

**Comment by abdallahmehiz** [comment]
i have the exact same logic as the link you sent here
https://github.com/abdallahmehiz/mpvKt/blob/c1e544b27d0eb0031efd4c21066555c4df9e28c6/app/src/main/java/live/mehiz/mpvkt/ui/player/PlayerViewModel.kt#L337 though

**Comment by MrDark-code** [comment]
@abdallahmehiz look in this file also 

https://github.com/videolan/vlc-android/blob/master/application/vlc-android/src/org/videolan/vlc/gui/video/VideoPlayerActivity.kt#L939

https://github.com/videolan/vlc-android/blob/master/application/vlc-android/src/org/videolan/vlc/gui/video/VideoPlayerActivity.kt#L1821
