### ISSUE TITLE
Customisation and optimisation suggestions 

### ISSUE THREAD

**Issue by P0bo** [abdallahmehiz/mpvKt#60]
|![Screenshot_2024-09-08-16-43-04-45_b93262821ba13b7694bb5d76b5032d4b](https://github.com/user-attachments/assets/1201b2d7-8bda-4354-b06b-1ebc0f99605d)|![Screenshot_2024-09-08-16-43-21-79_b93262821ba13b7694bb5d76b5032d4b](https://github.com/user-attachments/assets/5b01108e-364a-4b60-b9f9-1db0485658e5)|![Screenshot_2024-09-08-16-43-49-30_b93262821ba13b7694bb5d76b5032d4b](https://github.com/user-attachments/assets/3c08758f-0aa3-442e-a851-941d622ae7e8)|
|-|-|-|

- I would love if there is an option to choose between transparent style and solid style background , I personally prefer solid background but im sure many people prefer transparent background and it also makes sense since on phones the solid background may obstruct subtitle when adjusting sub delay or audio delay but on tablet its not much of a big deal sice the screen is much bigger.

|![Screenshot_2024-09-08-16-44-55-96_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/user-attachments/assets/ce249d7b-1290-4954-9cdb-b4e3dd248b26)|![Screenshot_2024-09-08-16-44-17-73_b93262821ba13b7694bb5d76b5032d4b](https://github.com/user-attachments/assets/657851d5-863e-4d80-8c2b-b86defbceb11)|
|-|-|

- I have noticed that even on tablets the audio switching and subtitle switching components appear as bottom sheet , it will be great if it was a card just like the filter , sub delay  , audio delay components when its in tablet mode . I think it would look nicer that way in tablets (example aniyomi).

**Comment by abdallahmehiz** [comment]
With the amount of settings I've been adding recently, I should probably add some backup/restore feature

**Comment by NikunjKhangwal** [comment]
> With the amount of settings I've been adding recently, I should probably add some backup/restore feature

This app is really going to become what mpv is on pc lol.
