### ISSUE TITLE
App crashing 

### ISSUE THREAD

**Issue by venttarc** [abdallahmehiz/mpvKt#61]
**Describe the bug**
The player crashes sometimes like 4 out of 10 times when I select videos from file and play it with mpvKt

**To Reproduce**
1. Go to 'File Manager'
2. Click on 'the video you wanna play'
3. See error
(I've given log too.Please check)

[New file.txt](https://github.com/user-attachments/files/16922557/New.file.txt)

**Additional info (please complete the following information):**
 - Device: OPPO A78 4G
 - Android version: 14
 - App Version 0.1.4

**Additional context**

**Comment by abdallahmehiz** [comment]
This has been fixed, it will soon be released.

**Comment by abdallahmehiz** [comment]
You can download the version with the fix from the github actions here 
https://github.com/abdallahmehiz/mpvKt/actions/workflows/nightlies.yml

Sorry for the inconvenience.

**Comment by venttarc** [comment]
> You can download the version with the fix from the github actions here https://github.com/abdallahmehiz/mpvKt/actions/workflows/nightlies.yml
> 
> Sorry for the inconvenience.

Thanks, I am already using latest nightly builds right after I had opened the issue. Thanks for replying fast.
