### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MrDark-code** [abdallahmehiz/mpvKt#63]
App version: 0.1.4 (ad62b84)
Android version: 10 (29)
Device brand: Redmi
Device manufacturer: Xiaomi
Device model: M2003J15SC (merlinnfc)
MPV version: v0.38.0-743-gad7976c33e
ffmpeg version: 0b6d7cd9d9
libplacebo version: v7.349.0 (v7.349.0-9-gefb89342)
      
      Exception:
      androidx.startup.StartupException: lateinit property fileName has not been initialized
	at live.mehiz.mpvkt.ui.player.PlayerActivity$event$3.invokeSuspend(SourceFile:116)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:15)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f34a6b8, Dispatchers.IO]

      
      Logcat:

**Comment by MrDark-code** [comment]
The crash error was caused by opening a link of this type:

https://vk146-2.vkuser.net/?expires=1726082214055&srcIp=128.204.65.152&pr=40&srcAg=UNKNOWN_ANDROID&ms=178.178.106.99&type=5&subId=7300623502032&sig=4p3w5KawGXo&ct=0&urls=45.136.21.163%3B185.226.52.168&clientType=13&appId=512000384397&zs=132&id=7300408347344

**Comment by abdallahmehiz** [comment]
I'll look into it tomorrow, thanks for the report.

**Comment by MrDark-code** [comment]
mpv.conf:

log-file=/storage/emulated/0/mpvlog.txt

file not created, i think because there is no permission to the file manager
![Screenshot_2024-09-09-11-35-27-538_com google android permissioncontroller](https://github.com/user-attachments/assets/2306d827-22e1-448d-a987-521f9048e313)
![Screenshot_2024-09-09-11-35-09-873_com google android permissioncontroller](https://github.com/user-attachments/assets/009fafa0-db4d-4b42-9c77-e4740c1dbffe)

**Comment by abdallahmehiz** [comment]
> The crash error was caused by opening a link of this type (link is not static):
> 
> https://vkvd206.mycdn.me/?expires=1726110057013&srcIp=128.204.65.13&pr=40&srcAg=UNKNOWN_ANDROID&ms=45.136.21.205&type=5&subId=6768006335101&sig=235ATKDS87Q&ct=0&urls=45.136.22.203&clientType=13&appId=512000384397&zs=132%3B11&id=6767891516029

Seems like it expired 😔

**Comment by MrDark-code** [comment]
@abdallahmehiz 

https://vkvd206.mycdn.me/?expires=1726114147251&srcIp=128.204.65.12&pr=40&srcAg=UNKNOWN_ANDROID&ms=45.136.21.205&type=5&subId=6768006335101&sig=dmaFvMb-hGU&ct=0&urls=45.136.22.203&clientType=13&appId=512000384397&zs=132%3B11&id=6767891516029

**Comment by MrDark-code** [comment]
I tried adding it to the manifest:

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

it didn't work

**Comment by abdallahmehiz** [comment]
You can select an mpvKt configuration directory and place the log file there...

**Comment by MrDark-code** [comment]
@abdallahmehiz 
log not created.
![Screenshot_2024-09-09-12-30-48-829_live mehiz mpvkt](https://github.com/user-attachments/assets/716a7a5b-861a-4c7a-9b7c-2b586646ede9)

**Comment by abdallahmehiz** [comment]
you're giving it permission to the root of shared storage? I don't know if android allows that...

**Comment by MrDark-code** [comment]
@abdallahmehiz 
yes I do and only the mpv.conf configuration file is created

**Comment by abdallahmehiz** [comment]
I think that's cause I am creating it using Android's SAF, but mpv can't make SAF calls...

**Comment by abdallahmehiz** [comment]
Also... you shouldn't do that (choosing the entirety of your shared storage as an mpv configuration). Cause what the app is doing, is copying every single file in there recursively to its application directory...
make sure to clear your mpv configuration from the settings.

**Comment by MrDark-code** [comment]
@abdallahmehiz 
I deleted the same from the settings the log was not created.

**Comment by abdallahmehiz** [comment]
> I think that's cause I am creating it using Android's SAF, but mpv can't make SAF calls...

Just like i said, mpv can't create log files on shared storage (at least without `WRITE_EXTERNAL_STORAGE` permission) even if you set the config dir.

**Comment by MrDark-code** [comment]
@abdallahmehiz 
yes the file was created only in 
/data/data/live.mehiz.mpvkt/files

**Comment by abdallahmehiz** [comment]
Btw, can you provide me a new, regenerated link so I can debug the crash?

**Comment by MrDark-code** [comment]
@abdallahmehiz 

https://vk146-1.vkuser.net/?srcIp=128.204.65.73&pr=40&expires=1726325826071&srcAg=UNKNOWN_ANDROID&fromCache=1&ms=178.178.106.98&type=5&subId=6768006335101&sig=fzGDEYPS2SE&ct=0&urls=45.136.21.205%3B45.136.22.203&clientType=13&appId=512000384397&zs=132&id=6767891516029

**Comment by MrDark-code** [comment]
@abdallahmehiz 

What did you do to make it work smoothly with gpu-next with the gpu-hq profile ? Goes smoothly )

**Comment by abdallahmehiz** [comment]
Didn't do anything special...
Maybe it's because you have the YUV420P pixel format enabled in the settings (enabled by default), which from my testing, increases performance a lot.

**Comment by abdallahmehiz** [comment]
well then I am not sure what's causing it, I have applied any kind of optimizations.

**Comment by MrDark-code** [comment]
@abdallahmehiz 

In mpv goes poorly there, but mpvkt does great.

**Comment by abdallahmehiz** [comment]
Why is that :thinking:
