### ISSUE TITLE
Add more mimeType extensions to handle different links

### ISSUE THREAD

**Issue by nvllz** [abdallahmehiz/mpvKt#65]
Could you please consider adding these to the `AndroidManifest.xml` file? The app does not show up for .m3u8 links in the Linksheet app bottom menu, the last line should fix it. There are also other popular extensions, based on the file linked below.

```
<data android:mimeType="*/mkv" />
<data android:mimeType="application/mp4" />
<data android:mimeType="application/mpeg*" />
<data android:mimeType="application/x-extension-mp4" />
<data android:mimeType="application/x-mpegURL" />
```

In case of this not working please take a look [here](https://github.com/VideoExpertsGroup/RTSP.Player.Android/blob/master/AndroidManifest.xml) and [here](https://android.googlesource.com/platform/external/mime-support/+/9817b71a54a2ee8b691c1dfa937c0f9b16b3473c/mime.types).

**Comment by abdallahmehiz** [comment]
I've just deleted the new release before i forgot something, i'll look into this meanwhile

**Comment by abdallahmehiz** [comment]
While at it, can you give me an example of an m3u8 link i can test with?

**Comment by abdallahmehiz** [comment]
> @abdallahmehiz unfortunately it still doesn't show up for .m3u8 links, unlike NextPlayer :/

Their android manifest doesn't contain any mimetypes wth
https://github.com/anilbeesetti/nextplayer/blob/main/app/src/main/AndroidManifest.xml

**Comment by abdallahmehiz** [comment]
mpvKt is actually showing up in the share sheet when trying to share this url for me...

**Comment by abdallahmehiz** [comment]
You mean like the verified links page in an app's settings page?

**Comment by abdallahmehiz** [comment]
Just tested with the app and cb4a92eca8da84adfc94d869130840ac51fa8d02 should fix it

**Comment by abdallahmehiz** [comment]
I've basically copied what mpv-android was doing, though you may be right, this might become annoying. I will make some changes to it.
