### ISSUE TITLE
More balanced volume step value

### ISSUE THREAD

**Issue by nvllz** [abdallahmehiz/mpvKt#66]
Version 0.1.5 introduces revised volume handling. I'm not sure if it's hardcoded or device dependent, but when I try to change the volume, the step value is 7. I find it too big, would love a more resonable value for this, or some kind of setting like the double tap to seek duration preference. While 7 seems acceptable for volume button action, it's expected to be more subtle for vertical gesture. Maybe just make it like 2 for gesture only if possible? Just to prevent fast accidental volume increases, but still leave the way to quickly change the volume with physical buttons.

**Comment by abdallahmehiz** [comment]
That 7 is a percentage no? can you try disabling the show volume as percentage option in the player settings?

**Comment by abdallahmehiz** [comment]
15 steps is the amount specified by the vendor though. most phones can go higher or lower depending on the device, I can't control that...

**Comment by abdallahmehiz** [comment]
I am not sure how Samsung's tools amplify your device's audio but since the system stills gives mpvKt the value of 15 steps it's probably some software mixer they've installed, which I can't do anything about.

**Comment by abdallahmehiz** [comment]
Yep, my device has 15 volume steps so it increments by 7% each step.

**Comment by abdallahmehiz** [comment]
Oh no, It's how an android thing. Every media player on android has this.

**Comment by abdallahmehiz** [comment]
I guess I can close the issue now? Or are there any other questions?

**Comment by abdallahmehiz** [comment]
> Is it really not possible or too complex to make it the way other apps handle it?

It is possible, but implementing will add a lot of complexity especially when handling stuff like media session and background playback

> because it's a way in other video players like Cloudstream, NextPlayer and audio players (any you will pick).

On my end, NextPlayer does the exact same thing of incrementing by 7%, so does VLC, MX, and mpv-android.

> If there's some Android barrier, I'm sorry for my lack of knowledge.

The only way i can see this be done in (of the top of my head) is to set the device's volume to max and then control the media volume from the audio decoder's mixer. Which, to be frank, isn't a good solution.
