### ISSUE TITLE
[BUG] Subtitle delay utility applies to both subtitles

### ISSUE THREAD

**Issue by 77-77SP** [abdallahmehiz/mpvKt#68]
When using the text heard/audio seen subtitle utility, the change is made to both primary and secondary subtitles instead of the chosen subtitle only. This behavior should only occur when "both" option is used.

Tested on version 0.1.5

Thank you

**Comment by abdallahmehiz** [comment]
From my testing, this isn't happening... and the delay is getting applied to the chosen subtitle correctly...

**Comment by 77-77SP** [comment]
> From my testing, this isn't happening... and the delay is getting applied to the chosen subtitle correctly...

I tested it again and while it is correct that the delay is getting applied to the selected subtitle only, the delay input value can be seen in primary, secondary and both.

**Comment by abdallahmehiz** [comment]
more of a UI bug then, should be fixed in 6901e1c2f723ae271220f879db852a36338950c4

**Comment by 77-77SP** [comment]
> more of a UI bug then, should be fixed in 6901e1c2f723ae271220f879db852a36338950c4

Understood, thank you for your time.
