### ISSUE TITLE
Bug: player lock has lost it's meaning (existential crises)

### ISSUE THREAD

**Issue by Brajesh3** [abdallahmehiz/mpvKt#7]
You play a video then lock the player to prevent accidental touch

But you can still seek video & 
change brightness & volume.

**Comment by abdallahmehiz** [comment]
Seems like the `areControlsLocked` state changing isn't affecting modifiers when recomposing for some reason. I've made the necessary changes for that not to happen and it'll be fixed soon. Thanks for the bug report :+1:

**Comment by abdallahmehiz** [comment]
Should be fixed in 7cf5b4d9bec654c3f44165358a92a73abac1ecd8

**Comment by Brajesh3** [comment]
Is this by design or bug that 2x speed still works even when player locked

**Comment by abdallahmehiz** [comment]
Definitely a bug I didn't catch.
sleep deprived programming...
I'll be deleting the latest release and making a new one.

**Comment by Brajesh3** [comment]
Sorry for the frequent disturbance
Light should not dim when player lock has been applied

![Screenshot_20240901-141841_mpvKt](https://github.com/user-attachments/assets/99eea002-834e-463f-a3c7-3162a7466ff4)

![Screenshot_20240901-141837_mpvKt](https://github.com/user-attachments/assets/398672a2-c2eb-41a3-b58a-19b1c9c63f54)

![Screenshot_20240901-141828_mpvKt](https://github.com/user-attachments/assets/27723c4a-db84-45a2-b21e-0f18abd10213)

![Screenshot_20240901-141823_mpvKt](https://github.com/user-attachments/assets/411e3c04-ec3a-4380-87bb-3075a841bdc2)
