### ISSUE TITLE
Error remembering position for video URL

### ISSUE THREAD

**Issue by MrDark-code** [abdallahmehiz/mpvKt#72]
Hi does not remember the position in the video URL correctly. When, for example, you start watching a new episode of a series, the position should be at 00:00, but it automatically switches to the previous position.

**Comment by abdallahmehiz** [comment]
... Why don't you guys use the bug report template...
Can you reopen it with more context? and use the bug report template.

**Comment by MrDark-code** [comment]
@abdallahmehiz 
the error itself does not occur, it’s just that when you watch the URL of the video, it remembers the position, but when you open the next video, viewing starts from the previous position, and not from the beginning

**Comment by abdallahmehiz** [comment]
That's on network videos, right?
I can't do much about those since the url changes from session to session many times with different arguments and such...
the current logic of remember just searches for if a video with the same file name was already played and apply the last position.
file names from urls change a lot.

**Comment by MrDark-code** [comment]
@abdallahmehiz 

https://www.dropbox.com/scl/fi/3cbon6h9i45s12lwq3myk/Screenrecorder-2024-09-11-20-17-06-430.mp4?rlkey=k4vix1zp2ioqoqoxau10mu7zc&dl=1

**Comment by MrDark-code** [comment]
The most interesting thing is that this does not happen in all URL protocols

**Comment by abdallahmehiz** [comment]
i don't think the protocol got anything to do with it.
just to make sure.
can you intercept the urls being opened by mpv with an app like [App Manager](https://github.com/MuntashirAkon/AppManager)? see if they change each time you try to play them.

**Comment by MrDark-code** [comment]
for individual series they are different, but the url stream for the same series does not change yet

**Comment by MrDark-code** [comment]
@abdallahmehiz 

I remember this used to be fixed in Precise mpv in the build version starting from 2.9.6
