### ISSUE TITLE
Bug/missing feature when seeking back

### ISSUE THREAD

**Issue by Rickyrvxlovet** [abdallahmehiz/mpvKt#74]
**Describe the bug**
When i try to search back the OSD message is wrong. while in the original mpv android it's ok.

**To Reproduce**
1. Go to 'file picker'
2. Click on 'the file'
3. Play the video
4. try to seek back

**Expected behavior**
Display this OSD message
--00:06
[15:11].

**Actual behavior**
Displays the wrong osd msg
+00:00
[15:11]

**Screenshots**
Original mpv-android :
![IMG_20240912_124142](https://github.com/user-attachments/assets/76a7e051-66ce-45c4-a16e-23811cbe96e1)
mpvKt :
![IMG_20240912_125000](https://github.com/user-attachments/assets/207ee962-db1a-476b-bed1-dd683d8363ca)

**Additional info (please complete the following information):**
 - Device: Redmi note 11d
 - Android version: 13
 - App Version : Nightly 0.1.5-158

**Additional context**

**Comment by abdallahmehiz** [comment]
Looks ok to me.
![Screenshot_20240912-110914](https://github.com/user-attachments/assets/8a5d481e-0ea8-4a35-ada3-3ca0478c205b)

**Comment by abdallahmehiz** [comment]
i am on release 0.1.5

**Comment by abdallahmehiz** [comment]
Yep, i've made a regression, will be swiftly fixed
