### ISSUE TITLE
Feature request : Subtitle scale for ass subtitles 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [abdallahmehiz/mpvKt#78]
Add a factor for the Text Subtitle Font Size option in Subtitles<Miscellaneous<Sub-scale  
for ass Subtitles 

1-User can adjust the subtitle size by a bar on right.
2-User can hold a subtitle-frame and then adjust it by zooming.

**Comment by abdallahmehiz** [comment]
You'll need to enable ASS override for it to work...
I guess I'll replace it with scale then.
