### ISSUE TITLE
Feature request : Add audio mode

### ISSUE THREAD

**Issue by zhengqwe** [abdallahmehiz/mpvKt#80]
Add audio mode, like VLC, it can play pure audio content. VLC has problems playing some audio m3u8 links.

**Comment by abdallahmehiz** [comment]
You mean a music player UI?

**Comment by aqtoo** [comment]
I think they mean a way so it just plays the audio of a file so they can listen to it in the background, I would also like an audio button.

**Comment by abdallahmehiz** [comment]
the it's a duplicate of #10
