### ISSUE TITLE
Add battery and hour to the screen 

### ISSUE THREAD

**Issue by Nicardpop** [abdallahmehiz/mpvKt#90]
![image0](https://github.com/user-attachments/assets/91a4aeaf-eba1-4732-af01-96dfd56b25cd)

**Comment by odopo** [comment]
Which player is in that screen shot?

**Comment by abdallahmehiz** [comment]
Any suggestions on where on the ui to place it?

**Comment by Nicardpop** [comment]
> Which player is in that screen shot?
> 
> Also, as a stop-gap measure you can probably use scripts to display that. I've previously used a script I created with Bing Copilot for always displaying time in mpv-android. I haven't tried it in mpvKt though.

>The player on the screen is named "MI video" its my phone default player

**Comment by Nicardpop** [comment]
> Any suggestions on where on the ui to place it?

just like the one I sent, its a natural place of the battery bar in a smartphone ! At the end is up to  u <3

**Comment by Bihanabdu** [comment]
![Uploading Screenshot_20240923_064642_XPlayer - Video Player.jpg…]()

**Comment by Bihanabdu** [comment]
![Uploading Screenshot_20240923_064642_XPlayer - Video Player.jpg…]()

**Comment by Bihanabdu** [comment]
![Screenshot_20240923_064642_XPlayer - Video Player](https://github.com/user-attachments/assets/a832eb67-ef9d-4e4d-a9ee-3d5059d137cd)
